### ISSUE TITLE
Software version for reproducibility

### ISSUE THREAD

**Issue by FL512** [WeiWei060512/NUMTs-detection#4]
Dear Wei,

First of all, thank you very much for sharing a fantastic tools for us.
We really appreciate it.

My colleague and I are interested in analyzing NUMTs using your established pipeline.
It will be of great if we know which version of software you used in the pipeline.
Typically, could you please let us know the version of perl and samtools (and blat if possible) used in NUMTs detection.sh?

Thank you in advance,
Ken

https://github.com/WeiWei060512/NUMTs-detection/blob/master/scripts/NUMTs_detection.sh
module load samblaster/0.1.24
module load samtools 
module load Sambamba/0.6.6

**Comment by WeiWei060512** [comment]
Hi Ken,
Thanks for reaching out. You can find the versions in our online publication. 

Best,
Wei

**Comment by FL512** [comment]
Hi Wei,

Thank you for your response.

I found most of the version info at
https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-022-05288-7/MediaObjects/41586_2022_5288_MOESM2_ESM.pdf
Thank you!

Do you mind if ask a few more things?
Which version of the perl did you use when you established the NUMTs?
Are you an Ubuntu user or a CentOS user?

Happy holidays!
Ken

**Comment by WeiWei060512** [comment]
I used perl 5. 
I ran my analysis on Genomics England Research Environment.

Wei

**Comment by FL512** [comment]
Thank you again for letting me know!!
Ken
